"""Prior-authorization packet schema — PriorAuthPacket model.

Output artifact containing the prior-auth summary, clinical justification,
documentation checklist, and submission readiness flags.
"""

from datetime import datetime, timezone

from pydantic import BaseModel, Field, model_validator


class ChecklistItem(BaseModel):
    item: str
    resolved: bool

class PriorAuthPacket(BaseModel):
    """Payer-ready prior-authorization packet.

    Generated by the serializer service after entity validation passes.
    """

    session_id: str = Field(..., description="Owning session")
    summary: str = Field(..., description="Human-readable prior auth summary")
    clinical_justification: str = Field(
        ..., description="Extracted rationale formatted for payer"
    )
    documentation_checklist: list[ChecklistItem] = Field(
        default_factory=list,
        description="Items required for submission",
    )
    missing_fields_resolved: list[str] = Field(
        default_factory=list,
        description="Fields that were missing but have been resolved",
    )
    ready_for_submission: bool = Field(
        default=False,
        description="True only if missing_fields_resolved is True",
    )
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="When this packet was generated (UTC)",
    )
    payer_template: str | None = Field(
        default=None,
        description="Optional payer-specific template name",
    )

    model_config = {"str_strip_whitespace": True}
